name: Documentation
description: Suggest documentation improvements
title: "[Docs]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Help improve CachePilot documentation.

  - type: dropdown
    id: document
    attributes:
      label: Documentation Area
      options:
        - README.md
        - API.md
        - SECURITY.md
        - CONFIGURATION.md
        - DEPLOYMENT.md
        - FRONTEND.md
        - CONTRIBUTING.md
        - CLI help text
        - Code comments
        - Other
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Issue Type
      options:
        - Missing information
        - Incorrect information
        - Unclear/confusing
        - Outdated
        - Typo/grammar
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be improved?
      placeholder: Describe the documentation issue...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Proposed Changes
      description: How should it be improved?
      placeholder: Suggest improvements...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
