name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Suggest a new feature or improvement for CachePilot.

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which area would this feature affect?
      options:
        - CLI
        - API
        - Frontend
        - Monitoring
        - Backup/Restore
        - Security
        - Performance
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve?
      placeholder: Describe the problem or limitation...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this work?
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other solutions you've considered
      placeholder: List alternative approaches...

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How would this improve CachePilot?
      placeholder: Explain the benefits...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I'm willing to implement this feature
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other relevant information
