#!/usr/bin/env bash
#
# CachePilot - Network Performance Tuning Script
#
# Optimizes system-level TCP/IP and memory settings for Redis network performance.
# This script creates kernel parameter configurations for optimal Redis operation
# over network connections.
#
# Author: Patrick Schlesinger <cachepilot@msrv-digital.de>
# Version: 2.1.2-Beta
# License: MIT
#

set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root${NC}"
   exit 1
fi

echo "=========================================="
echo "Redis Network Performance Tuning"
echo "=========================================="
echo ""
echo "This will optimize system-level TCP/IP parameters for:"
echo "  • Higher connection capacity"
echo "  • Lower network latency"
echo "  • Better throughput"
echo "  • Reduced memory overhead"
echo ""
echo -e "${YELLOW}Note: Changes require system reboot to take full effect${NC}"
echo ""
read -p "Apply system-level tuning? (y/N): " CONFIRM

if [[ ! "$CONFIRM" =~ ^[Yy]$ ]]; then
    echo "Tuning cancelled."
    exit 0
fi

echo ""
echo "Creating /etc/sysctl.d/99-redis-performance.conf..."

cat > /etc/sysctl.d/99-redis-performance.conf << 'EOF'
#
# Redis Network Performance Tuning
# Generated by CachePilot
#
# These settings optimize the Linux kernel for Redis network performance
#

# Network Socket Settings
# Increase maximum connection backlog (important for many simultaneous connections)
net.core.somaxconn = 65535

# TCP Settings
# Increase SYN backlog for better connection handling
net.ipv4.tcp_max_syn_backlog = 8192

# Reduce FIN timeout for faster connection cleanup
net.ipv4.tcp_fin_timeout = 30

# Enable TCP socket reuse for better performance
net.ipv4.tcp_tw_reuse = 1

# Disable TCP slow start after idle (better for Redis keep-alive connections)
net.ipv4.tcp_slow_start_after_idle = 0

# Memory Management
# Allow Redis to overcommit memory (important for fork operations)
vm.overcommit_memory = 1

# Disable THP (Transparent Huge Pages) which can cause latency issues
vm.nr_hugepages = 0

# Network Buffer Sizes
# Increase TCP receive buffer size
net.ipv4.tcp_rmem = 4096 87380 16777216

# Increase TCP send buffer size
net.ipv4.tcp_wmem = 4096 65536 16777216

# Increase maximum socket buffer size
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216

# Connection Tracking
# Increase connection tracking table size (if using iptables/firewall)
net.netfilter.nf_conntrack_max = 1048576
EOF

echo -e "${GREEN}✓${NC} Configuration file created"
echo ""

# Apply settings immediately
echo "Applying settings..."
if sysctl -p /etc/sysctl.d/99-redis-performance.conf > /dev/null 2>&1; then
    echo -e "${GREEN}✓${NC} Settings applied successfully"
else
    echo -e "${YELLOW}⚠${NC} Some settings may require reboot"
fi

# Disable Transparent Huge Pages (THP) - recommended by Redis
echo ""
echo "Disabling Transparent Huge Pages (THP)..."

# Create systemd service to disable THP at boot
cat > /etc/systemd/system/disable-thp.service << 'EOF'
[Unit]
Description=Disable Transparent Huge Pages (THP)
DefaultDependencies=no
After=sysinit.target local-fs.target
Before=redis.service

[Service]
Type=oneshot
ExecStart=/bin/sh -c 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
ExecStart=/bin/sh -c 'echo never > /sys/kernel/mm/transparent_hugepage/defrag'

[Install]
WantedBy=basic.target
EOF

systemctl daemon-reload
systemctl enable disable-thp.service > /dev/null 2>&1
systemctl start disable-thp.service > /dev/null 2>&1

echo -e "${GREEN}✓${NC} THP disabled"

# Docker Daemon Optimization
echo ""
echo "Configuring Docker daemon for performance..."

cat > /etc/docker/daemon.json << 'EOF'
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "10m",
    "max-file": "3"
  },
  "default-address-pools": [
    {
      "base": "172.17.0.0/12",
      "size": 24
    }
  ],
  "mtu": 1500,
  "storage-driver": "overlay2",
  "userland-proxy": false
}
EOF

systemctl daemon-reload
systemctl restart docker

echo -e "${GREEN}✓${NC} Docker daemon configured"

echo ""
echo "=========================================="
echo -e "${GREEN}✓ Network Tuning Complete${NC}"
echo "=========================================="
echo ""
echo "Applied optimizations:"
echo "  • TCP connection capacity: 65535 (from ~128)"
echo "  • TCP SYN backlog: 8192 (from ~512)"
echo "  • TCP FIN timeout: 30s (from 60s)"
echo "  • Memory overcommit: enabled"
echo "  • Transparent Huge Pages: disabled"
echo "  • Network buffers: optimized"
echo ""
echo -e "${YELLOW}For optimal performance: Reboot the system${NC}"
echo ""
echo "Verify current settings:"
echo "  sysctl net.core.somaxconn"
echo "  sysctl vm.overcommit_memory"
echo "  cat /sys/kernel/mm/transparent_hugepage/enabled"
echo ""
